apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: kubernetes
  version: 0.1.0
  annotations:
    categories: Kubernetes
    chartDescription: Injects kubernetes chaos experiment
spec:
  displayName: Kubernetes Chaos
  categoryDescription: >
    Kubernetes is an open-source system for automating deployment, scaling, and management of containerized applications. It groups containers that make up an application into logical units for easier management and discovery. It will install all the experiments which can be used to inject chaos into containerized applications.
  experiments:
    - name: pod-delete
      description: It injects pod-delete chaos on a kubernetes pod
    - name: container-kill
      description: It injects container-kill chaos on a kubernetes pod 
    - name: pod-cpu-hog
      description: It injects cpu-hog chaos on a kubernetes pod
    - name: pod-network-loss
      description: It injects network-loss chaos on a kubernetes pod
    - name: pod-network-latency
      description: It injects network-latency chaos on a kubernetes pod
    - name: pod-network-corruption
      description: It injects network-corruption chaos on a kubernetes pod
    - name: node-drain
      description: It injects node-drain chaos on a kubernetes node
    - name: node-network-loss
      description: It injects network loss chaos on a kubernetes node
    - name: node-cpu-hog
      description: It injects node-cpu-hog chaos on a kubernetes node
    - name: node-network-latency
      description: It injects node-network-latency chaos on a kubernetes node
    - name: node-restart
      description: It injects node-restart chaos on a kubernetes node
    - name: disk-fill
      description: It injects disk-fill chaos on a kubernetes node
    - name: node-memory-hog
      description: It injects node-memory-hog chaos on a kubernetes node
    - name: pod-memory-hog
      description: It injects pod-memory-hog chaos on a kubernetes pod
    - name: kubelet-service-kill
      description: It injects kubelet-service-kill chaos on a kubernetes
    - name: pod-network-duplication
      description: It injects pod-network-duplication chaos on a kubernetes pod
    - name: node-taint
      description: It injects node-taint chaos on a kubernetes node
    - name: docker-service-kill
      description: It injects docker-service-kill chaos on a kubernetes pod
    - name: pod-autoscaler
      description: It injects pod-autoscaler chaos on a kubernetes pod
    - name: node-io-stress
      description: It injects node-io-stress chaos on a kubernetes node
    - name: pod-io-stress
      description: It injects pod-io-stress chaos on a kubernetes pod
    - name: pod-dns-error
      description: It injects pod-dns-error chaos on a kubernetes pod
    - name: pod-dns-spoof
      description: It injects pod-dns-spoof chaos on a kubernetes pod
    - name: pod-cpu-hog-exec
      description: It injects pod-cpu-hog-exec chaos on a kubernetes pod
    - name: pod-memory-hog-exec
      description: It injects pod-memory-hog-exec chaos on a kubernetes pod
    - name: pod-network-partition
      description: It injects pod-network-partition chaos on a kubernetes pod
    - name: pod-http-latency
      description: It injects pod-http-latency chaos on a kubernetes pod
    - name: pod-http-status-code
      description: It injects pod-http-status-code chaos on a kubernetes pod
    - name: pod-http-modify-header
      description: It injects pod-http-modify-header chaos on a kubernetes pod
    - name: pod-http-modify-body
      description: It injects pod-http-modify-body chaos on a kubernetes pod
    - name: pod-http-reset-peer
      description: It injects pod-http-reset-peer chaos on a kubernetes pod
  keywords:
    - Kubernetes
  maintainers:
    - name: ksatchit
      email: karthik.s@harness.io
  minKubeVersion: 1.12.0
  provider:
    name: Harness
  links:
    - name: Kubernetes Website
      url: https://kubernetes.io
    - name: Source Code
      url: https://github.com/kubernetes/kubernetes
    - name: Kubernetes Slack
      url: https://slack.kubernetes.io/
    - name: Documentation
      url: https://litmuschaos.github.io/litmus/experiments/categories/contents/#kubernetes
  icon:
    - url: https://raw.githubusercontent.com/litmuschaos/charthub.litmuschaos.io/master/public/litmus.ico
      mediatype: image/png
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/experiments.yaml
